services:
  frontend:
    build: 
      context: ./client
      dockerfile: Dockerfile
    container_name: RTF-frontend
    image: rtf-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app 
      - /app/node_modules
  backend:
    container_name: RTF-backend
    image: rtf-backend
    ports:
      - "9000:9000"
